<?php 
/*

!!VALIDATING FORM INPUT: DROP-DOWN MENUS!!

> want to make sure that a valid choice was selected from a drop-down menu generated by the HTML <select/> element

*in_array - checks if a value exists in an array - searches haystack for needle using loose comparison unless strict is set (always strict)
*array_key_exists - checks if the given key or index exists in the array

*/

/*Use an array of values to generate the menu. Then validate the input by checking that the value is in the array*/
/*Validating a drop-down menu with in_array()*/
// Generating the menu
$choices = array('Eggs', 'Toast', 'Coffee');

print "<select name='food'>\n";
foreach($choices as $choice) {
	print "<option>$choice</option>\n";
}
print "</select>";

// Then, later, validating the menu
if(!in_array($_POST['food'], $choices)) {
	print 'You must select a valid choice.';
}
?>

<!--GENERATED DROP-DOWN MENU-->
<select name='food'>
<option>Eggs</option>
<option>Toast</option>
<option>Coffee</option>
</select>


<?php 
/*To work with a menu that sets value attributes on each <option/> element, use array_key_exists() to validate the input*/
/*Validating a drop-down menu with array_key_exists()*/
// Generating the menu
$choices = array(
	'eggs'	=>	'Eggs Benedict',
	'toast'   =>	'Buttered Toast with Jam',
	'coffee'  =>	'Pipping Hot Coffe'	
);

print "<select menu='food'>\n";
foreach($choices as $key => $choice) {
	print "<option value='$key'>$choice</option>\n";
}
print "</select>";

// Then, later, validating the menu
if(!array_key_exists($_POST['food'], $choices)) {
	print 'You must select a valid choice';
}
?>

<!--GENERATED DROP-DOWN MENU-->
<select name='food'>
<option value='eggs'>Eggs Benedict</option>
<option value='toast'>Buttered Toast with Jam</option>
<option value='coffee'>Piping Hot Coffee</option>
</select>